-- Rules-engine fix, no schema change: Instability's "give one of your
-- moods back" choice is now genuinely asked AFTER the taken mood has
-- actually changed ownership, instead of being bundled into the same
-- pending-decision batch as the opponent's own "which mood to give up"
-- choice. Previously the given-mood choice was validated (and rendered)
-- against the board as it stood BEFORE the exchange, and an explicit
-- `$givenCardId === $takenCardId` check additionally blocked giving the
-- just-taken mood straight back -- both now fixed: the acting player can
-- legally hand back the exact card they just received, the same way
-- giving Instability itself away already worked. This migration exists
-- purely to keep schema_version in sync with the VERSION bump, the same
-- way 0024/0025/0026/0037/0040/0044/0045/0046/0052/0056/0058 already did
-- for their own schema-less changes -- MaintenanceGate compares the
-- deployed VERSION file against this table on every request (see
-- migration 0021's own docblock), so a VERSION bump with no matching
-- schema_version update would show maintenance mode after deploy even
-- though nothing about the schema actually changed.
UPDATE schema_version SET version = '1.6.2' WHERE id = 1;
