-- New feature, no schema change: adds GameService::deleteStaleCompletedGames()/
-- expireStaleActiveGames() and bin/expire_and_delete_stale_games.php, a
-- once-daily cron completing issue #84's cleanup work (the "Past games"
-- split from migration 0061 only moved old completed games to a
-- different list -- this actually deletes/force-ends them once they've
-- been stale for 7+ days). No new tables/columns -- game_events.event_type
-- is a plain VARCHAR, so the new 'game_expired' value needs no schema
-- change either. This migration exists purely to keep schema_version in
-- sync with the VERSION bump, the same way 0024/0025/0026/0037/0040/
-- 0044/0045/0046/0052/0056/0058/0059/0060/0061 already did for their own
-- schema-less changes -- MaintenanceGate compares the deployed VERSION
-- file against this table on every request (see migration 0021's own
-- docblock), so a VERSION bump with no matching schema_version update
-- would show maintenance mode after deploy even though nothing about the
-- schema actually changed.
UPDATE schema_version SET version = '1.6.5' WHERE id = 1;
