-- Issue #189: 3-4 player Winston Draft.
--
-- No schema change needed: draft_winston_state.current_player_user_id
-- (a plain column, not a fixed 2-value toggle) and
-- last_draft_action_by_user_id (already a JSON map keyed by user_id,
-- from migrations 0035/0036) were already fully N-player-ready by
-- original design -- only GameService's own turn-order arithmetic and
-- pool-sizing constants needed to generalize:
--
-- - createGame() widens its 2-player gate for 'draft' + 'winston_draft'
--   the same way it already does for 'quick_draft'/'grid_draft'.
-- - WINSTON_POOL_SIZE/WINSTON_MIN_CUSTOM_POOL_SIZE (both a flat 45)
--   are replaced by winstonDraftPoolTargetSize($playerCount)/
--   winstonDraftMinCustomPoolSize($playerCount) -- 45/70/90 for
--   2/3/4 players. buildDraftPool()'s 'structure' pool source doubles
--   itself for 3-4 players (Winston Draft's own call site only), and its
--   'jceddys_75' source swaps to jceddy's 150 Card deck's own pool at
--   exactly 4 players, the same swap Quick Draft's and Grid Draft's own
--   4-player jceddys_75 case already gets.
-- - submitWinstonDraftPick()'s turn order generalizes from a fixed
--   2-player toggle to seat-index rotation, mathematically identical
--   to the old toggle at exactly 2 players.
-- - finalizeWinstonDraft() now only excludes the players who actually
--   came up short of WINSTON_MIN_DECK_SIZE (12) rather than ending the
--   whole match the moment anyone is short: 0 short players proceeds
--   normally; exactly 1 survivor degenerates to the original 2-player
--   auto-loss rule; 2+ survivors continue to deck_building as a smaller
--   match, with the short players' draft_match_players/game_players rows
--   removed entirely (safe pre-startGame(), since no game_cards/
--   game_rounds row anywhere yet references those seats).
UPDATE schema_version SET version = '1.9.0' WHERE id = 1;
