-- No schema change: widens the "past games" split (issue #84, see
-- migration 0021's own docblock) so an 'abandoned' game moves to
-- GET /games/past the same way a 'completed' one does, instead of sitting
-- in the main lobby forever (GameService::listGamesForUser()/
-- listPastGamesForUser()). This migration exists purely to keep
-- schema_version in sync with the VERSION bump, the same way
-- 0024/.../0068 already did for their own schema-less changes --
-- MaintenanceGate compares the deployed VERSION file against this table
-- on every request, so a VERSION bump with no matching schema_version
-- update would show maintenance mode after deploy even though nothing
-- about the schema actually changed.
UPDATE schema_version SET version = '1.10.8' WHERE id = 1;
