-- No schema change: adds Set/# columns, a set filter, pagination, and
-- corrected color/rarity sort order to the Stats page
-- (web-static/stats/index.html, web-static/js/stats.js), backed by a new
-- CardCatalog::loadSetInfo() helper on the existing sets/card_sets
-- tables (migration 0015) -- no new columns or tables needed. This
-- migration exists purely to keep schema_version in sync with the
-- VERSION bump, the same way 0024/.../0071 already did for their own
-- schema-less changes -- MaintenanceGate compares the deployed VERSION
-- file against this table on every request, so a VERSION bump with no
-- matching schema_version update would show maintenance mode after
-- deploy even though nothing about the schema actually changed.
UPDATE schema_version SET version = '1.11.2' WHERE id = 1;
