-- No schema change: adds a sort direction indicator (aria-sort +
-- CSS ::after arrow) to the Stats page's table headers
-- (web-static/js/stats.js, web-static/css/style.css), and makes
-- sortedFilteredCards() sort a copy instead of mutating the shared
-- `cards` array as a side effect of rendering. This migration exists
-- purely to keep schema_version in sync with the VERSION bump, the same
-- way 0024/.../0072 already did for their own schema-less changes --
-- MaintenanceGate compares the deployed VERSION file against this table
-- on every request, so a VERSION bump with no matching schema_version
-- update would show maintenance mode after deploy even though nothing
-- about the schema actually changed.
UPDATE schema_version SET version = '1.11.3' WHERE id = 1;
