-- No schema change: fixes the Discord deploy announcement's version-bump
-- filter to check only each commit's SUBJECT line (via git log's %s),
-- not the whole commit message body -- previously a commit whose body
-- happened to mention "Bump VERSION to X.Y.Z" (a bundled version-bump-
-- plus-fix commit, not a dedicated bump-only one) was dropped from the
-- changelog in its entirety, once producing "no new commits" for a
-- deploy that shipped a real change (.github/workflows/deploy.yml,
-- deploy-dev.yml). This migration exists purely to keep schema_version
-- in sync with the VERSION bump, the same way 0024/.../0077 already did
-- for their own schema-less changes -- MaintenanceGate compares the
-- deployed VERSION file against this table on every request, so a
-- VERSION bump with no matching schema_version update would show
-- maintenance mode after deploy even though nothing about the schema
-- actually changed.
UPDATE schema_version SET version = '1.11.8' WHERE id = 1;
