-- No schema change: fixes Duplicity's own "each time you play another
-- mood, you may have that mood's after-playing effect happen an
-- additional time" only ever repeating a card's own PRINTED
-- after-playing effect, never an attached chaos effect layered on top
-- of it. MoodPlayService::resolveAttachedChaosAfterPlaying() now fires
-- once per Duplicity-repeated invocation instead of once per play. See
-- php-app/README.md's "Chaos Draft" section.
-- This migration exists purely to keep schema_version in sync with the
-- VERSION bump that shipped alongside this fix, the same way 0024/.../0185
-- already did for their own schema-less changes -- MaintenanceGate
-- compares the deployed VERSION file against this table on every request,
-- so a VERSION bump with no matching schema_version update leaves the app
-- showing maintenance mode after deploy even though nothing about the
-- schema actually changed.
UPDATE schema_version SET version = '1.28.42' WHERE id = 1;
